# Generator for OLEDDashboard bitmap icons (WiFi + battery).
# Emits src/Icons.h PROGMEM data. Run: python gen_icons.py
import math, io

W, H = 13, 11  # wifi icon size

def circle(g, cx, cy, r, ch='#'):
    """Draw the upper arc of a circle, sampling angles so adjacent pixels
    connect into a continuous curve."""
    steps = max(2 * r, 4) * 4
    prev = None
    for i in range(steps + 1):
        ang = math.pi * i / steps  # 0..pi (upper half)
        x = int(round(cx + r * math.cos(ang)))
        y = int(round(cy - r * math.sin(ang)))
        if 0 <= x < W and 0 <= y < H:
            g[y][x] = ch
            if prev:
                # connect to previous point to keep the curve continuous
                for (xx, yy) in bresenham(prev[0], prev[1], x, y):
                    if 0 <= xx < W and 0 <= yy < H:
                        g[yy][xx] = ch
        prev = (x, y)

def bresenham(x0, y0, x1, y1):
    pts = []
    dx = abs(x1 - x0)
    dy = -abs(y1 - y0)
    sx = 1 if x0 < x1 else -1
    sy = 1 if y0 < y1 else -1
    err = dx + dy
    while True:
        pts.append((x0, y0))
        if x0 == x1 and y0 == y1:
            break
        e2 = 2 * err
        if e2 >= dy:
            err += dy
            x0 += sx
        if e2 <= dx:
            err += dx
            y0 += sy
    return pts

def make_wifi(level):
    g = [['.' for _ in range(W)] for _ in range(H)]
    cx, cy = 6, 9
    if level >= 4: circle(g, cx, cy, 5)
    if level >= 3: circle(g, cx, cy, 3)
    if level >= 2: circle(g, cx, cy, 1)
    if level >= 1:
        g[cy - 1][cx] = '#'
        g[cy][cx] = '#'
    return g

def render(g):
    return [''.join(row) for row in g]

def emit_wifi(levels):
    lines = []
    lines.append("// Auto-generated by gen_icons.py -- DO NOT EDIT BY HAND.")
    lines.append("#include <Arduino.h>")
    lines.append("")
    lines.append("/// WiFi icon metrics.")
    lines.append("static constexpr int8_t kWifiIconW = %d;" % W)
    lines.append("static constexpr int8_t kWifiIconH = %d;" % H)
    lines.append("static constexpr int8_t kWifiLevelCount = 5;")
    lines.append("")
    lines.append("/// All WiFi signal bitmaps packed in a flat PROGMEM array.")
    lines.append("/// Bitmap for level L starts at [L * kWifiIconH].")
    lines.append("static const uint16_t sWifiIcons[%d * %d] PROGMEM = {" % (len(levels), H))
    for _, g in levels:
        for row in g:
            v = 0
            for ch in row:
                v = (v << 1) | (1 if ch == '#' else 0)
            lines.append("    0x%04X," % v)
    lines.append("};")
    lines.append("")
    return "\n".join(lines)

def battery_outline():
    # 14 wide x 7 tall. Body 0..11, nub 12..13 (rows 2..4).
    rows = []
    for y in range(7):
        line = ['.'] * 14
        for x in range(12):
            if y == 0 or y == 6:
                line[x] = '#'
            elif x == 0 or x == 11:
                line[x] = '#'
        if 2 <= y <= 4:
            line[12] = '#'
            line[13] = '#'
        rows.append(''.join(line))
    return rows

def bolt():
    # 6x6 charging bolt
    B = [
        ".#....",
        "###...",
        "####..",
        "..####",
        "...###",
        "....#.",
    ]
    return B

def warn():
    # 3x7 exclamation mark
    W2 = [
        ".#.",
        ".#.",
        ".#.",
        ".#.",
        ".#.",
        "...",
        ".#.",
    ]
    return W2

def emit_battery(rows, boltrows, warnrows):
    lines = []
    lines.append("/// Battery body bitmap (14x7), nub on the right.")
    lines.append("static constexpr int8_t kBatteryW = 14;")
    lines.append("static constexpr int8_t kBatteryH = 7;")
    lines.append("static const uint16_t sBatteryOutline[kBatteryH] PROGMEM = {")
    for r in rows:
        v = 0
        for ch in r:
            v = (v << 1) | (1 if ch == '#' else 0)
        lines.append("    0x%04X," % v)
    lines.append("};")
    lines.append("")
    lines.append("/// Charging bolt bitmap (6x6).")
    lines.append("static constexpr int8_t kBoltW = 6;")
    lines.append("static constexpr int8_t kBoltH = 6;")
    lines.append("static const uint8_t sBatteryBolt[kBoltH] PROGMEM = {")
    for r in boltrows:
        v = 0
        for ch in r:
            v = (v << 1) | (1 if ch == '#' else 0)
        lines.append("    0x%02X," % v)
    lines.append("};")
    lines.append("")
    lines.append("/// Low-battery warning bitmap (3x7).")
    lines.append("static constexpr int8_t kWarnW = 3;")
    lines.append("static constexpr int8_t kWarnH = 7;")
    lines.append("static const uint8_t sBatteryWarn[kWarnH] PROGMEM = {")
    for r in warnrows:
        v = 0
        for ch in r:
            v = (v << 1) | (1 if ch == '#' else 0)
        lines.append("    0x%02X," % v)
    lines.append("};")
    lines.append("")
    return "\n".join(lines)

def main():
    levels = []
    for lvl in range(5):
        levels.append((lvl, make_wifi(lvl)))
    out = r"C:\Users\user\Documents\JuanPersonal\OLEDLib\OLEDDashboard\src\Icons.h"
    parts = [
        "/*",
        " * Icons.h -- custom bitmap icons for OLEDDashboard.",
        " *",
        " * Contains PROGMEM bitmaps for the WiFi signal (5 levels) and the",
        " * battery (outline, charging bolt, low-battery warning). Generated by",
        " * gen_icons.py; do not edit by hand.",
        " */",
        "#ifndef OLED_DASHBOARD_ICONS_H",
        "#define OLED_DASHBOARD_ICONS_H",
        "#include <Arduino.h>",
        "",
        emit_wifi(levels),
        emit_battery(battery_outline(), bolt(), warn()),
        "#endif  // OLED_DASHBOARD_ICONS_H",
        "",
    ]
    text = "\n".join(parts)
    with io.open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("Wrote", out, len(text), "bytes")
    for lvl, g in levels:
        print("--- wifi level %d" % lvl)
        for r in render(g):
            print(r)
    print("--- battery outline")
    for r in battery_outline():
        print(r)
    print("--- bolt")
    for r in bolt():
        print(r)
    print("--- warn")
    for r in warn():
        print(r)

if __name__ == "__main__":
    main()
