/*
 * Icons.h -- custom bitmap icons for OLEDDashboard.
 *
 * Contains PROGMEM bitmaps for the WiFi signal (5 levels) and the
 * battery (outline, charging bolt, low-battery warning). Generated by
 * gen_icons.py; do not edit by hand.
 */
#ifndef OLED_DASHBOARD_ICONS_H
#define OLED_DASHBOARD_ICONS_H
#include <Arduino.h>

// Auto-generated by gen_icons.py -- DO NOT EDIT BY HAND.
#include <Arduino.h>

/// WiFi icon metrics.
static constexpr int8_t kWifiIconW = 13;
static constexpr int8_t kWifiIconH = 11;
static constexpr int8_t kWifiLevelCount = 5;

/// All WiFi signal bitmaps packed in a flat PROGMEM array.
/// Bitmap for level L starts at [L * kWifiIconH].
static const uint16_t sWifiIcons[5 * 11] PROGMEM = {
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0040,
    0x0040,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x00E0,
    0x00E0,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x00F0,
    0x0110,
    0x02E8,
    0x02E8,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x01F0,
    0x071C,
    0x04F4,
    0x0D16,
    0x0AEA,
    0x0AEA,
    0x0000,
};

/// Battery body bitmap (14x7), nub on the right.
static constexpr int8_t kBatteryW = 14;
static constexpr int8_t kBatteryH = 7;
static const uint16_t sBatteryOutline[kBatteryH] PROGMEM = {
    0x3FFC,
    0x2004,
    0x2007,
    0x2007,
    0x2007,
    0x2004,
    0x3FFC,
};

/// Charging bolt bitmap (6x6).
static constexpr int8_t kBoltW = 6;
static constexpr int8_t kBoltH = 6;
static const uint8_t sBatteryBolt[kBoltH] PROGMEM = {
    0x10,
    0x38,
    0x3C,
    0x0F,
    0x07,
    0x02,
};

/// Low-battery warning bitmap (3x7).
static constexpr int8_t kWarnW = 3;
static constexpr int8_t kWarnH = 7;
static const uint8_t sBatteryWarn[kWarnH] PROGMEM = {
    0x02,
    0x02,
    0x02,
    0x02,
    0x02,
    0x00,
    0x02,
};

#endif  // OLED_DASHBOARD_ICONS_H
